### ISSUE TITLE
pubs init TypeError

### ISSUE THREAD

**Issue by clement-moulin-frier** [pubs/pubs#27]
After having installed pubs using "python setup.py develop", as well as the required dependencies, I have the following error when running "pubs init":

```
$ pubs init
Initializing pubs in /home/clement/.pubs
Traceback (most recent call last):
  File "/usr/local/bin/pubs", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/clement/Documents/Boulot/GENERAL/CODE/pubs/pubs/pubs", line 5, in <module>
    pubs_cmd.execute()
  File "/home/clement/Documents/Boulot/GENERAL/CODE/pubs/pubs/pubs_cmd.py", line 90, in execute
    cmd_funcs[cmd](args)
  File "/home/clement/Documents/Boulot/GENERAL/CODE/pubs/pubs/commands/init_cmd.py", line 45, in command
    config().save()
  File "/home/clement/Documents/Boulot/GENERAL/CODE/pubs/pubs/configs.py", line 75, in save
    self._cfg.write(f)
  File "/usr/lib/python2.7/ConfigParser.py", line 407, in write
    fp.write("[%s]\n" % section)
TypeError: must be unicode, not str
```

**Comment by framecurrent** [comment]
Same problem. Any solutions?

**Comment by humm** [comment]
Ok, so I finally managed to reproduce the error, and tracked down its origin. It's not pretty. It boils down to the config module being hopelessly broken, and python 2 (which I assume you are using) being reeeally messy with str and unicode. I committed a quick fix, but I won't probably work if you have something else than ascii characters in your path. 

I won't be able to provide much support in the next weeks---this is a very alpha stage right now, but an overhaul of the code base to make it much more robust will happen soon.

**Comment by framecurrent** [comment]
Thanks, it works now! Hope you can find time to continue the development.

**Comment by 73** [comment]
Hi guys,
this is actually not fixed:
```
[$] pubs init
Initializing pubs in /Users/73/.pubs
Traceback (most recent call last):
  File "/Users/73/Downloads/test_pubs/venv/bin/pubs", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/73/Downloads/test_pubs/pubs/pubs/pubs", line 5, in <module>
    pubs_cmd.execute()
  File "/Users/73/Downloads/test_pubs/pubs/pubs/pubs_cmd.py", line 90, in execute
    cmd_funcs[cmd](args)
  File "/Users/73/Downloads/test_pubs/pubs/pubs/commands/init_cmd.py", line 44, in command
    config().save()
  File "/Users/73/Downloads/test_pubs/pubs/pubs/configs.py", line 75, in save
    self._cfg.write(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 407, in write
    fp.write("[%s]\n" % section)
TypeError: must be unicode, not str
```
What can I do to help out?

Best,
73

**Comment by humm** [comment]
Hey, the last commits seemed to have broken a few (a lot of) things. I am on it, I am trying to have this fixed by tomorrow. It seems you are using OS X. What version of python are you using?

**Comment by 73** [comment]
Thanks for getting back to me that quickly.
I'm running 2.7.10_2 from `homebrew` on my OSX box. 
I would like to give `pubs` a spin and maybe even help out.

**Comment by humm** [comment]
Ok, this should work now. Tell me if it does not.

I am going to be rewritting some of the more fragile part of the codebase in the next few days. It's going to be a little bumpy (the configuration file is going to be overhauled next), but I am interested by and will pay close attention to the issues you uncover during usage.

**Comment by 73** [comment]
works. thanks. I'll evaluate whether or not `pubs` is for me. If it is there might come some PRs ;)
